name: Network_security  

on:
  push:
    branches:
      - main
    paths-ignore:  
      - 'README.md'  

jobs:
  preprocessed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Lint code
        run: echo "Linting Repo" 

      - name: Run unit test
        run: echo "Running unit test"  



